-- MySQL Script generated by MySQL Workbench
-- Tue Oct 31 16:17:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema osbb_jdbc1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema osbb_jdbc1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `osbb_jdbc1` DEFAULT CHARACTER SET utf8 ;
USE `osbb_jdbc1` ;

-- -----------------------------------------------------
-- Table `osbb_jdbc1`.`buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb_jdbc1`.`buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb_jdbc1`.`flats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb_jdbc1`.`flats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` TINYINT(2) NOT NULL,
  `sq` FLOAT NOT NULL,
  `building_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_building_idx` (`building_id` ASC) VISIBLE,
  CONSTRAINT `fk_building`
    FOREIGN KEY (`building_id`)
    REFERENCES `osbb_jdbc1`.`buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb_jdbc1`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb_jdbc1`.`people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tel_number` INT NOT NULL,
  `parking` TINYINT(1) NOT NULL DEFAULT 0,
  `flats_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flats_idx` (`flats_id` ASC) VISIBLE,
  CONSTRAINT `fk_flats`
    FOREIGN KEY (`flats_id`)
    REFERENCES `osbb_jdbc1`.`flats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb_jdbc1`.`people_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb_jdbc1`.`people_roles` (
  `people_id` INT NOT NULL,
  `role` ENUM('STAFF', 'RESIDENT', 'PRESIDENT', 'NULL') NOT NULL,
  INDEX `fk_people2role_idx` (`people_id` ASC) INVISIBLE,
  INDEX `idx_role` (`role` ASC) VISIBLE,
  CONSTRAINT `fk_people2role`
    FOREIGN KEY (`people_id`)
    REFERENCES `osbb_jdbc1`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb_jdbc1`.`people_owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb_jdbc1`.`people_owner` (
  `people_id_owner` INT NOT NULL,
  `owner` TINYINT(1) NOT NULL DEFAULT 0,
  INDEX `fk_people_owner_idx` (`people_id_owner` ASC) VISIBLE,
  CONSTRAINT `fk_people_owner`
    FOREIGN KEY (`people_id_owner`)
    REFERENCES `osbb_jdbc1`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb_jdbc1`.`peole_inhabitant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb_jdbc1`.`peole_inhabitant` (
  `people_id_inhabitant` INT NOT NULL,
  `inhabitant` TINYINT(1) NOT NULL DEFAULT 0,
  INDEX `fk_people_inh_idx` (`people_id_inhabitant` ASC) VISIBLE,
  CONSTRAINT `fk_people_inhabitant`
    FOREIGN KEY (`people_id_inhabitant`)
    REFERENCES `osbb_jdbc1`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
